


try{
    console.log(eval("1+2+7#5"));
}

catch(err){
    console.log("error occured");
}

finally{
    console.log("completed");
}